version: 2
aliases:
  - &java_container
    image: "circleci/openjdk:8"
    environment:
      _JAVA_OPTIONS: "-Xmx1536m"
  - &orika_spring_boot_starter_dependencies_cache_key >-
    orika-spring-boot-starter-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &orika_spring_boot_starter_sample_dependencies_cache_key >-
    orika-spring-boot-starter-sample-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &checkout
    checkout:
      path: "~/orika-spring-boot-starter"
  - &attach_workspace
    attach_workspace:
      at: "~/orika-spring-boot-starter-workspace"
  - &restore_from_workspace
    run:
      name: "Restoring from workspace"
      command: "cp --archive --verbose ~/orika-spring-boot-starter-workspace/. ~"
jobs:
  build_and_test_orika_spring_boot_starter:
    docker:
      - *java_container
    working_directory: "~/orika-spring-boot-starter/orika-spring-boot-starter"
    steps:
      - *checkout
      - restore_cache:
          key: *orika_spring_boot_starter_dependencies_cache_key
      - run:
          name: "Building and testing"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *orika_spring_boot_starter_dependencies_cache_key
          paths:
            - "~/.m2"
      - run:
          name: "Uploading Codecov reports"
          command: "curl --silent https://codecov.io/bash | bash"
      - store_test_results:
          path: "target/surefire-reports"
      - store_artifacts:
          path: "target"
          destination: "/"
      - persist_to_workspace:
          root: "~"
          paths:
            - ".m2/repository/net/rakugakibox/spring/boot/orika-spring-boot-starter"
  build_orika_spring_boot_starter_sample:
    docker:
      - *java_container
    working_directory: "~/orika-spring-boot-starter/orika-spring-boot-starter-sample"
    steps:
      - *checkout
      - *attach_workspace
      - *restore_from_workspace
      - restore_cache:
          key: *orika_spring_boot_starter_sample_dependencies_cache_key
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *orika_spring_boot_starter_sample_dependencies_cache_key
          paths:
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_orika_spring_boot_starter
      - build_orika_spring_boot_starter_sample:
          requires:
            - build_and_test_orika_spring_boot_starter
