version: 2
jobs:
  build-and-test-orika-spring-boot-starter:
    docker:
      - image: "openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/orika-spring-boot-starter/orika-spring-boot-starter"
    steps:
      - checkout:
          path: "~/orika-spring-boot-starter"
      - restore_cache:
          key: 'orika-spring-boot-starter-dependencies-{{ checksum "pom.xml" }}'
      - run:
          name: "Building and testing"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'orika-spring-boot-starter-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
      - run:
          name: "Upload Codecov reports"
          command: "curl --silent https://codecov.io/bash | bash"
      - store_test_results:
          path: "target/surefire-reports"
      - store_artifacts:
          path: "target"
          destination: "/"
      - persist_to_workspace:
          root: "~/.m2/repository/net/rakugakibox/spring/boot/orika-spring-boot-starter"
          paths:
            - "*"
            - "*/*"
  build-orika-spring-boot-starter-sample:
    docker:
      - image: "openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/orika-spring-boot-starter/orika-spring-boot-starter-sample"
    steps:
      - checkout:
          path: "~/orika-spring-boot-starter"
      - restore_cache:
          key: 'orika-spring-boot-starter-sample-dependencies-{{ checksum "pom.xml" }}'
      - attach_workspace:
          at: "~/.m2/repository/net/rakugakibox/spring/boot/orika-spring-boot-starter"
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'orika-spring-boot-starter-sample-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-orika-spring-boot-starter
      - build-orika-spring-boot-starter-sample:
          requires:
            - build-and-test-orika-spring-boot-starter
